### PR TITLE
Bug Fix: Error message is stripped if stack exists

### PR DESCRIPTION
**Pull request by nickmaltsev**
#32

### CODE REVIEW

**Comment by AriaMinaei** [comment]
Thanks for the PR! Could you check why the build fails? Also, let's add one or more test cases for this specific case. I'm reviewing this on mobile, but first glance tells me that the this code may not be able to handle multi line messages, but I'm not sure

**Comment by nickmaltsev** [comment]
@AriaMinaei resolve test issues, add multiline test case

**Comment by AriaMinaei** [comment]
Great! Allow me to test this on Thursday and publish to npm by then :)

**Comment by AriaMinaei** [comment]
Published as RC

**Comment by alexparish** [comment]
@AriaMinaei I see the RC was published some time ago. Is this ready for a 2.2.0 release?

**Comment by AriaMinaei** [comment]
Yeah this has been left unmerged for a long time. Sorry about that :)

I just added a line in the readme asking people to try out the RC.

**Comment by texastoland** [comment]
Status?

**Pull request merged**
